export const MENUITEMS = [
  {
    title: "Projects",
    submenu: ["Residential", "Commercial", "Healthcare", "Interior"],
  },
  {
    title: "About",
  },
  {
    title: "Contact",
  },
  {
    title: "Scope of Work",
  },
];

export const BUILDINGDATAHOMEPAGE = [
  {
    id: 3,
    name: "AN House",
    type: "Residential",
    image_url: "https://iili.io/hhVrMX.jpg",
  },
  {
    id: 1,
    name: "BA House",
    type: "Residential",
    image_url: "https://iili.io/XycIeV.jpg",
  },
  {
    id: 20, //ganti FA bedroom
    name: "FA Bedroom",
    type: "Interior",
    image_url: "https://iili.io/jlRFmG.jpg",
  },
  {
    id: 6,
    name: "TD Bakehouse",
    type: "Commercial",
    image_url: "https://iili.io/hhhq6F.jpg",
  },
  {
    id: 16,
    name: "KJ Clinic",
    type: "Healthcare",
    image_url: "https://iili.io/hhwyan.jpg",
  },
];

export const BUILDINGDATA = [
  {
    id: 0,
    name: "JD House",
    type: "Residential",
    image_url: [
      "https://iili.io/XtIsnI.jpg",
      "https://iili.io/XtILGt.jpg",
      "https://iili.io/XtIQ6X.jpg",
      "https://iili.io/XtItFn.jpg",
      "https://iili.io/XtIPZN.jpg",
    ],
    collab_detail: "Ikrar Raksaperdana, Andro Aquila",
    type_detail: "Ikrar Raksaperdana, Andro Aquila",
    location_detail: "Pasteur, Bandung",
    status_detail: "Desain - Design",
    area_detail: "400",
    IMAGES: [
      {
        original: "https://iili.io/XtIsnI.jpg",
        thumbnail: "https://iili.io/XtIsnI.jpg",
      },
      {
        original: "https://iili.io/XtILGt.jpg",
        thumbnail: "https://iili.io/XtILGt.jpg",
      },
      {
        original: "https://iili.io/XtIQ6X.jpg",
        thumbnail: "https://iili.io/XtIQ6X.jpg",
      },
      {
        original: "https://iili.io/XtItFn.jpg",
        thumbnail: "https://iili.io/XtItFn.jpg",
      },
      {
        original: "https://iili.io/XtIPZN.jpg",
        thumbnail: "https://iili.io/XtIPZN.jpg",
      },
    ],
  },
  {
    id: 1,
    name: "BA House",
    type: "Residential",
    image_url: [
      "https://iili.io/XycTmB.jpg",
      "https://iili.io/Xyc2bS.jpg",
      "https://iili.io/XycC0b.jpg",
      "https://iili.io/Xycz5Q.jpg",
      "https://iili.io/XycIeV.jpg",
      "https://iili.io/XycTmB.jpg",
      "https://iili.io/Xyc5LF.jpg",
      "https://iili.io/XycYqg.jpg",
      "https://iili.io/XycEep.jpg",
      "https://iili.io/XycGmN.jpg",
      "https://iili.io/XycWXt.jpg",
      "https://iili.io/XycXLX.jpg",
      "https://iili.io/Xyce2f.jpg",
      "https://iili.io/Xyc8p2.jpg",
      "https://iili.io/Xyc6Be.jpg",
      "https://iili.io/XycQYx.jpg",
      "https://iili.io/XyctpV.jpg",
      "https://iili.io/Xyl9CF.jpg",
      "https://iili.io/Xyl3Yv.jpg",
      "https://iili.io/XylFvR.jpg",
      "https://iili.io/XylBjI.jpg",
      "https://iili.io/XylT3G.jpg",
      "https://iili.io/XylRyl.jpg",
      "https://iili.io/XylYjS.jpg",
      "https://iili.io/XylG3b.jpg",
    ],
    collab_detail: "-",
    type_detail: "Residensial - Residential",
    location_detail: "Pasteur, Bandung",
    status_detail: "Selesai - Completed",
    area_detail: "150",
    IMAGES: [
      {
        original: "https://iili.io/XycTmB.jpg",
        thumbnail: "https://iili.io/XycTmB.jpg",
      },
      {
        original: "https://iili.io/Xyc2bS.jpg",
        thumbnail: "https://iili.io/Xyc2bS.jpg",
      },
      {
        original: "https://iili.io/XycC0b.jpg",
        thumbnail: "https://iili.io/XycC0b.jpg",
      },
      {
        original: "https://iili.io/Xycz5Q.jpg",
        thumbnail: "https://iili.io/Xycz5Q.jpg",
      },
      {
        original: "https://iili.io/XycIeV.jpg",
        thumbnail: "https://iili.io/XycIeV.jpg",
      },
      {
        original: "https://iili.io/XycTmB.jpg",
        thumbnail: "https://iili.io/XycTmB.jpg",
      },
      {
        original: "https://iili.io/Xyc5LF.jpg",
        thumbnail: "https://iili.io/Xyc5LF.jpg",
      },
      {
        original: "https://iili.io/XycYqg.jpg",
        thumbnail: "https://iili.io/XycYqg.jpg",
      },
      {
        original: "https://iili.io/XycEep.jpg",
        thumbnail: "https://iili.io/XycEep.jpg",
      },
      {
        original: "https://iili.io/XycGmN.jpg",
        thumbnail: "https://iili.io/XycGmN.jpg",
      },
      {
        original: "https://iili.io/XycWXt.jpg",
        thumbnail: "https://iili.io/XycWXt.jpg",
      },
      {
        original: "https://iili.io/XycXLX.jpg",
        thumbnail: "https://iili.io/XycXLX.jpg",
      },
      {
        original: "https://iili.io/Xyce2f.jpg",
        thumbnail: "https://iili.io/Xyce2f.jpg",
      },
      {
        original: "https://iili.io/Xyc8p2.jpg",
        thumbnail: "https://iili.io/Xyc8p2.jpg",
      },
      {
        original: "https://iili.io/Xyc6Be.jpg",
        thumbnail: "https://iili.io/Xyc6Be.jpg",
      },
      {
        original: "https://iili.io/XycQYx.jpg",
        thumbnail: "https://iili.io/XycQYx.jpg",
      },
      {
        original: "https://iili.io/XyctpV.jpg",
        thumbnail: "https://iili.io/XyctpV.jpg",
      },
      {
        original: "https://iili.io/Xyl9CF.jpg",
        thumbnail: "https://iili.io/Xyl9CF.jpg",
      },
      {
        original: "https://iili.io/Xyl9CF.jpg",
        thumbnail: "https://iili.io/Xyl9CF.jpg",
      },
      {
        original: "https://iili.io/Xyl3Yv.jpg",
        thumbnail: "https://iili.io/Xyl3Yv.jpg",
      },
      {
        original: "https://iili.io/XylFvR.jpg",
        thumbnail: "https://iili.io/XylFvR.jpg",
      },
      {
        original: "https://iili.io/XylBjI.jpg",
        thumbnail: "https://iili.io/XylBjI.jpg",
      },
      {
        original: "https://iili.io/XylT3G.jpg",
        thumbnail: "https://iili.io/XylT3G.jpg",
      },
      {
        original: "https://iili.io/XylRyl.jpg",
        thumbnail: "https://iili.io/XylRyl.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "PY House",
    type: "Residential",
    image_url: [
      "https://iili.io/hhVC3G.jpg",
      "https://iili.io/hhMp3J.jpg",
      "https://iili.io/hhMyYv.jpg",
      "https://iili.io/hhV9vR.jpg",
      "https://iili.io/hhVdTN.jpg",
      "https://iili.io/hhVKCX.jpg",
      "https://iili.io/hhVfGn.jpg",
      "https://iili.io/hhVq4s.jpg",
      "https://iili.io/hhVnaf.jpg",
      "https://iili.io/hhVov4.jpg",
      "https://iili.io/hhVxyl.jpg",
      "https://iili.io/hhVIu2.jpg",
      "https://iili.io/hhVTjS.jpg",
      "https://iili.io/hhVuZ7.jpg",
      "https://iili.io/hhVRn9.jpg",
      "https://iili.io/hhV5Ge.jpg",
      "https://iili.io/hhV76u.jpg",
      "https://iili.io/hhVa3b.jpg",
      "https://iili.io/hhVcaj.jpg",
      "https://iili.io/hhVl8x.jpg",
      "https://iili.io/hhV0yQ.jpg",
      "https://iili.io/hhVGwB.jpg",
      "https://iili.io/hhVMZP.jpg",
      "https://iili.io/hhVWn1.jpg",
      "https://iili.io/hhVXMF.jpg",
      "https://iili.io/hhVh6g.jpg",
      "https://iili.io/hhVwFa.jpg",
      "https://iili.io/hhVNcJ.jpg",
    ],
    collab_detail: "-",
    type_detail: "Residensial - Residential",
    location_detail: "Antapani, Bandung",
    status_detail: "Desain - Design",
    area_detail: "240",
    IMAGES: [
      {
        original: "https://iili.io/hhVC3G.jpg",
        thumbnail: "https://iili.io/hhVC3G.jpg",
      },
      {
        original: "https://iili.io/hhMp3J.jpg",
        thumbnail: "https://iili.io/hhMp3J.jpg",
      },
      {
        original: "https://iili.io/hhMyYv.jpg",
        thumbnail: "https://iili.io/hhMyYv.jpg",
      },
      {
        original: "https://iili.io/hhV9vR.jpg",
        thumbnail: "https://iili.io/hhV9vR.jpg",
      },
      {
        original: "https://iili.io/hhVdTN.jpg",
        thumbnail: "https://iili.io/hhVdTN.jpg",
      },
      {
        original: "https://iili.io/hhVKCX.jpg",
        thumbnail: "https://iili.io/hhVKCX.jpg",
      },
      {
        original: "https://iili.io/hhVfGn.jpg",
        thumbnail: "https://iili.io/hhVfGn.jpg",
      },
      {
        original: "https://iili.io/hhVq4s.jpg",
        thumbnail: "https://iili.io/hhVq4s.jpg",
      },
      {
        original: "https://iili.io/hhVnaf.jpg",
        thumbnail: "https://iili.io/hhVnaf.jpg",
      },
      {
        original: "https://iili.io/hhVov4.jpg",
        thumbnail: "https://iili.io/hhVov4.jpg",
      },
      {
        original: "https://iili.io/hhVxyl.jpg",
        thumbnail: "https://iili.io/hhVxyl.jpg",
      },
      {
        original: "https://iili.io/hhVIu2.jpg",
        thumbnail: "https://iili.io/hhVIu2.jpg",
      },
      {
        original: "https://iili.io/hhVTjS.jpg",
        thumbnail: "https://iili.io/hhVTjS.jpg",
      },
      {
        original: "https://iili.io/hhVuZ7.jpg",
        thumbnail: "https://iili.io/hhVuZ7.jpg",
      },
      {
        original: "https://iili.io/hhVRn9.jpg",
        thumbnail: "https://iili.io/hhVRn9.jpg",
      },
      {
        original: "https://iili.io/hhV5Ge.jpg",
        thumbnail: "https://iili.io/hhV5Ge.jpg",
      },
      {
        original: "https://iili.io/hhV76u.jpg",
        thumbnail: "https://iili.io/hhV76u.jpg",
      },
      {
        original: "https://iili.io/hhVa3b.jpg",
        thumbnail: "https://iili.io/hhVa3b.jpg",
      },
      {
        original: "https://iili.io/hhVcaj.jpg",
        thumbnail: "https://iili.io/hhVcaj.jpg",
      },
      {
        original: "https://iili.io/hhVl8x.jpg",
        thumbnail: "https://iili.io/hhVl8x.jpg",
      },
      {
        original: "https://iili.io/hhV0yQ.jpg",
        thumbnail: "https://iili.io/hhV0yQ.jpg",
      },
      {
        original: "https://iili.io/hhVGwB.jpg",
        thumbnail: "https://iili.io/hhVGwB.jpg",
      },
      {
        original: "https://iili.io/hhVMZP.jpg",
        thumbnail: "https://iili.io/hhVMZP.jpg",
      },
      {
        original: "https://iili.io/hhVWn1.jpg",
        thumbnail: "https://iili.io/hhVWn1.jpg",
      },
      {
        original: "https://iili.io/hhVXMF.jpg",
        thumbnail: "https://iili.io/hhVXMF.jpg",
      },
      {
        original: "https://iili.io/hhVh6g.jpg",
        thumbnail: "https://iili.io/hhVh6g.jpg",
      },
    ],
  },
  {
    id: 3,
    name: "AN House",
    type: "Residential",
    image_url: [
      "https://iili.io/XycTmB.jpg",
      "https://iili.io/hhV8wN.jpg",
      "https://iili.io/hhVStI.jpg",
      "https://iili.io/hhVgnt.jpg",
      "https://iili.io/hhVrMX.jpg",
      "https://iili.io/hhV4Pn.jpg",
      "https://iili.io/hhVPFs.jpg",
      "https://iili.io/hhVicG.jpg",
      "https://iili.io/hhVsSf.jpg",
      "https://iili.io/hhVQ94.jpg",
      "https://iili.io/hhVZAl.jpg",
      "https://iili.io/hhVtN2.jpg",
      "https://iili.io/hhVDtS.jpg",
      "https://iili.io/hhVmo7.jpg",
      "https://iili.io/hhVpV9.jpg",
      "https://iili.io/hhVyPe.jpg",
      "https://iili.io/hhWHKu.jpg",
      "https://iili.io/hhWJcb.jpg",
      "https://iili.io/hhWdSj.jpg",
      "https://iili.io/hhW3Hx.jpg",
      "https://iili.io/hhWFAQ.jpg",
      "https://iili.io/hhWKNV.jpg",
      "https://iili.io/hhWfDB.jpg",
      "https://iili.io/hhWBoP.jpg",
      "https://iili.io/hhWCV1.jpg",
      "https://iili.io/hhWniF.jpg",
      "https://iili.io/hhWxKg.jpg",
      "https://iili.io/hhWzla.jpg",
      "https://iili.io/hhWIUJ.jpg",
      "https://iili.io/hhWuHv.jpg",
      "https://iili.io/hhWARR.jpg",
      "https://iili.io/hhWRNp.jpg",
      "https://iili.io/hhW5DN.jpg",
      "https://iili.io/hhWYxI.jpg",
      "https://iili.io/hhWciX.jpg",
      "https://iili.io/hhWEUG.jpg",
      "https://iili.io/hhWMJf.jpg",
      "https://iili.io/hhWVR4.jpg",
      "https://iili.io/hhWWOl.jpg",
    ],
    collab_detail: "-",
    type_detail: "Residensial - Residential",
    location_detail: "Bojongkoneng, Bandung",
    status_detail: "Selesai - Completed",
    area_detail: "144",
    IMAGES: [],
  },
  {
    id: 4,
    name: "NV House",
    type: "Residential",
    image_url: [
      "https://iili.io/hhW6zB.jpg",
      "https://iili.io/hhWk0u.jpg",
      "https://iili.io/hhWvUb.jpg",
      "https://iili.io/hhWSJj.jpg",
      "https://iili.io/hhWU5x.jpg",
      "https://iili.io/hhWgOQ.jpg",
      "https://iili.io/hhWrbV.jpg",
      "https://iili.io/hhWis1.jpg",
      "https://iili.io/hhWLqF.jpg",
      "https://iili.io/hhWQ0g.jpg",
      "https://iili.io/hhWZga.jpg",
      "https://iili.io/hhWDdJ.jpg",
      "https://iili.io/hhWb5v.jpg",
      "https://iili.io/hhWmeR.jpg",
      "https://iili.io/hhWpbp.jpg",
      "https://iili.io/hhX9zN.jpg",
      "https://iili.io/hhXHXI.jpg",
      "https://iili.io/hhXJst.jpg",
      "https://iili.io/hhX2qX.jpg",
      "https://iili.io/hhX31n.jpg",
      "https://iili.io/hhXFgs.jpg",
      "https://iili.io/hhXfdG.jpg",
      "https://iili.io/hhXq7f.jpg",
      "https://iili.io/hhXBe4.jpg",
      "https://iili.io/hhXCml.jpg",
    ],
    collab_detail: "-",
    type_detail: "Residensial - Residential",
    location_detail: "Bintaro, Tangerang",
    status_detail: "Desain - Design Under Construction",
    area_detail: "",
    IMAGES: [],
  },
  {
    id: 5,
    name: "NL Villa",
    type: "Residential",
    image_url: [
      "https://iili.io/hhXjkv.jpg",
      "https://iili.io/hhXkQI.jpg",
      "https://iili.io/hhX8Bt.jpg",
    ],
    collab_detail: "Nickola Fauzan",
    type_detail: "Residensial - Residential",
    location_detail: "Purwakarta",
    status_detail: "Desain - Design ",
    area_detail: "800",
    IMAGES: [],
  },
  {
    id: 6,
    name: "TD - Bakehouse",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhfG1.jpg",
      "https://iili.io/hhXyYb.jpg",
      "https://iili.io/hhh9vj.jpg",
      "https://iili.io/hhhHyx.jpg",
      "https://iili.io/hhhdTQ.jpg",
      "https://iili.io/hhhdTQ.jpg",
      "https://iili.io/hhh3ZB.jpg",
      "https://iili.io/hhhKCP.jpg",
      "https://iili.io/hhhq6F.jpg",
      "https://iili.io/hhhC3g.jpg",
      "https://iili.io/hhhnaa.jpg",
      "https://iili.io/hhho8J.jpg",
    ],
    collab_detail: "-",
    type_detail: "Kafe - Cafe",
    location_detail: "Bintaro, Tangerang",
    status_detail: "Desain - Design (Under Construction)",
    area_detail: "90",
    IMAGES: [],
  },
  {
    id: 7,
    name: "CD - SoHo",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhRnI.jpg",
      "https://iili.io/hhhTjp.jpg",
      "https://iili.io/hhhuZN.jpg",
      "https://iili.io/hhh5Gt.jpg",
      "https://iili.io/hhh76X.jpg",
      "https://iili.io/hhhaFn.jpg",
    ],
    collab_detail: "-",
    type_detail: "Rumah Toko - SoHo",
    location_detail: "Indonesia",
    status_detail: "Desain - Design",
    area_detail: "500",
    IMAGES: [],
  },
  {
    id: 8,
    name: "JXB - Bikehub",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhNcu.jpg",
      "https://iili.io/hhh19f.jpg",
      "https://iili.io/hhhEu4.jpg",
      "https://iili.io/hhhGwl.jpg",
      "https://iili.io/hhhMt2.jpg",
      "https://iili.io/hhhWnS.jpg",
      "https://iili.io/hhhhP9.jpg",
      "https://iili.io/hhhwFe.jpg",
      "https://iili.io/hhhO8b.jpg",
      "https://iili.io/hhhk9j.jpg",
      "https://iili.io/hhhvAx.jpg",
      "https://iili.io/hhh8wQ.jpg",
      "https://iili.io/hhhStV.jpg",
      "https://iili.io/hhhgoB.jpg",
      "https://iili.io/hhhrMP.jpg",
    ],
    collab_detail: "Nickola Fauzan",
    type_detail: "Terminal dan Kafe - Bike Terminal",
    location_detail: "Jakarta, Indonesia",
    status_detail: "Desain - Design",
    area_detail: "100",
    IMAGES: [],
  },
  {
    id: 9,
    name: "Sudirman - Shopping Ground",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhZAv.jpg",
      "https://iili.io/hhhPKF.jpg",
      "https://iili.io/hhhicg.jpg",
      "https://iili.io/hhhsSa.jpg",
      "https://iili.io/hhhQHJ.jpg",
      "https://iili.io/hhhtNR.jpg",
      "https://iili.io/hhhDtp.jpg",
      "https://iili.io/hhhmoN.jpg",
      "https://iili.io/hhhpVI.jpg",
      "https://iili.io/hhhyPt.jpg",
    ],
    collab_detail: "Vania Asyiffa",
    type_detail: "Market Place",
    location_detail: "Sudirman, Bandung",
    status_detail: "Desain - Design",
    area_detail: "900",
    IMAGES: [],
  },
  {
    id: 10,
    name: "Braga - Office",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjJln.jpg",
      "https://iili.io/hhjHKX.jpg",
      "https://iili.io/hhjdSs.jpg",
      "https://iili.io/hhj3HG.jpg",
      "https://iili.io/hhjFRf.jpg",
      "https://iili.io/hhjKN4.jpg",
      "https://iili.io/hhjfDl.jpg",
      "https://iili.io/hhjBx2.jpg",
      "https://iili.io/hhjCVS.jpg",
      "https://iili.io/hhjni7.jpg",
    ],
    collab_detail: "Deby Sinantya",
    type_detail: "Office",
    location_detail: "Braga, Bandung",
    status_detail: "Desain - Design",
    area_detail: "100",
    IMAGES: [
      {
        original: "https://iili.io/hhjJln.jpg",
        thumbnail: "https://iili.io/hhjJln.jpg",
      },
      {
        original: "https://iili.io/hhjfDl.jpg",
        thumbnail: "https://iili.io/hhjfDl.jpg",
      },
    ],
  },

  {
    id: 11,
    name: "Muaro Jambi - Rest Area",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjXbR.jpg",
      "https://iili.io/hhjuHb.jpg",
      "https://iili.io/hhjARj.jpg",
      "https://iili.io/hhjROx.jpg",
      "https://iili.io/hhj5DQ.jpg",
      "https://iili.io/hhjYxV.jpg",
      "https://iili.io/hhjaWB.jpg",
      "https://iili.io/hhjciP.jpg",
      "https://iili.io/hhj0f1.jpg",
      "https://iili.io/hhj10F.jpg",
      "https://iili.io/hhjEUg.jpg",
      "https://iili.io/hhjMJa.jpg",
      "https://iili.io/hhjV5J.jpg",
      "https://iili.io/hhjWOv.jpg",
      "https://iili.io/hhjjxp.jpg",
      "https://iili.io/hhjwWN.jpg",
      "https://iili.io/hhjNsI.jpg",
      "https://iili.io/hhjeft.jpg",
      "https://iili.io/hhjk0X.jpg",
    ],
    collab_detail: "-",
    type_detail: "Rest Area",
    location_detail: "Jambi, Indonesia",
    status_detail: "Desain - Design",
    area_detail: "6200",
    IMAGES: [],
  },
  {
    id: 12,
    name: "Rekathirta - Office",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjSJs.jpg",
      "https://iili.io/hhjvgn.jpg",
      "https://iili.io/hhjU5G.jpg",
      "https://iili.io/hhjgef.jpg",
      "https://iili.io/hhjrb4.jpg",
      "https://iili.io/hhj6zl.jpg",
    ],
    collab_detail: "-",
    type_detail: "Office",
    location_detail: "Kota Baru Parahyangan, Bandung",
    status_detail: "Desain - Design",
    area_detail: "220",
    IMAGES: [],
  },
  {
    id: 13,
    name: "Agro Jabar - Warehouse",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjpmx.jpg",
      "https://iili.io/hhjDdu.jpg",
      "https://iili.io/hhjb5b.jpg",
      "https://iili.io/hhjmej.jpg",
      "https://iili.io/hhjpmx.jpg",
      "https://iili.io/hhw9zQ.jpg",
      "https://iili.io/hhwHXV.jpg",
      "https://iili.io/hhwJLB.jpg",
      "https://iili.io/hhw2qP.jpg",
      "https://iili.io/hhw311.jpg",
      "https://iili.io/hhwFrF.jpg",
    ],
    collab_detail: "-",
    type_detail: "Warehouse",
    location_detail: "Jawa Barat, Indoneisa",
    status_detail: "Desain - Design",
    area_detail: "200",
    IMAGES: [],
  },
  {
    id: 14,
    name: "Dustira HD - Interior",
    type: "Healthcare",
    image_url: [
      "https://iili.io/hhwBkJ.jpg",
      "https://iili.io/hhwq7a.jpg",
      "https://iili.io/hhwCmv.jpg",
      "https://iili.io/hhwoIR.jpg",
      "https://iili.io/hhwxXp.jpg",
    ],
    collab_detail: "-",
    type_detail: "Lobby Interior",
    location_detail: "Cimahi, Indonesia",
    status_detail: "Selesai - Completed",
    area_detail: "100",
    IMAGES: [],
  },
  {
    id: 15,
    name: "Widaningshi - RSIA",
    type: "Healthcare",
    image_url: [
      "https://iili.io/hhw52n.jpg",
      "https://iili.io/hhwTBI.jpg",
      "https://iili.io/hhwu1t.jpg",
      "https://iili.io/hhwArX.jpg",
      "https://iili.io/hhw52n.jpg",
      "https://iili.io/hhw77s.jpg",
      "https://iili.io/hhwapf.jpg",
      "https://iili.io/hhw0hl.jpg",
      "https://iili.io/hhw1Q2.jpg",
      "https://iili.io/hhwGBS.jpg",
      "https://iili.io/hhwME7.jpg",
      "https://iili.io/hhwV49.jpg",
      "https://iili.io/hhwX2e.jpg",
      "https://iili.io/hhwhYu.jpg",
      "https://iili.io/hhwwpj.jpg",
      "https://iili.io/hhwr3F.jpg",
      "https://iili.io/hhwsTv.jpg",
      "https://iili.io/hhwLjR.jpg",
      "https://iili.io/hhwtCN.jpg",
      "https://iili.io/hhwDGI.jpg",
      "https://iili.io/hhwb4t.jpg",
      "https://iili.io/hhwp3X.jpg",
    ],
    collab_detail: "Nickola Fauzan",
    type_detail: "Interior",
    location_detail: "Garut, Indonesia",
    status_detail: "Desain - Design",
    area_detail: "400",
    IMAGES: [],
  },
  {
    id: 16,
    name: "KJ - Clinic",
    type: "Healthcare",
    image_url: [
      "https://iili.io/hhNfGS.jpg",
      "https://iili.io/hhwyan.jpg",
      "https://iili.io/hhN9vs.jpg",
      "https://iili.io/hhNHyG.jpg",
      "https://iili.io/hhNduf.jpg",
      "https://iili.io/hhN2j4.jpg",
      "https://iili.io/hhN3Zl.jpg",
      "https://iili.io/hhNKn2.jpg",
      "https://iili.io/hhNq67.jpg",
      "https://iili.io/hhNCF9.jpg",
      "https://iili.io/hhNnae.jpg",
      "https://iili.io/hhNo8u.jpg",
      "https://iili.io/hhNxyb.jpg",
    ],
    collab_detail: "-",
    type_detail: "Interior",
    location_detail: "Jamika, Bandung",
    status_detail: "Desain - Design (Under Construction)",
    area_detail: "100",
    IMAGES: [],
  },
  {
    id: 17,
    name: "NV - Kitchen",
    type: "Interior",
    image_url: [
      "https://iili.io/hhNDDx.jpg",
      "https://iili.io/hhNsSe.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhOJl1.jpg",
      "https://iili.io/hhOdUF.jpg",
      "https://iili.io/hhO3Hg.jpg",
      "https://iili.io/hhOFRa.jpg",
      "https://iili.io/hhOKOJ.jpg",
    ],
    collab_detail: "-",
    type_detail: "Kitchen Interior",
    location_detail: "Bintaro, Tangerang",
    status_detail: "Selesai - Completed",
    area_detail: "40",
    IMAGES: [],
  },
  {
    id: 18,
    name: "Petojo - Office",
    type: "Interior",
    image_url: [
      "https://iili.io/hhOARs.jpg",
      "https://iili.io/hhOCVp.jpg",
      "https://iili.io/hhOniN.jpg",
      "https://iili.io/hhOxfI.jpg",
      "https://iili.io/hhOzlt.jpg",
      "https://iili.io/hhOuJn.jpg",
      "https://iili.io/hhOROG.jpg",
      "https://iili.io/hhO5bf.jpg",
      "https://iili.io/hhOYx4.jpg",
      "https://iili.io/hhOaWl.jpg",
      "https://iili.io/hhOcs2.jpg",
      "https://iili.io/hhO0fS.jpg",
      "https://iili.io/hhO107.jpg",
    ],
    collab_detail: "-",
    type_detail: "Office Interior",
    location_detail: "Petojo, Jakarta",
    status_detail: "Desain - Design ",
    area_detail: "120",
    IMAGES: [],
  },
  {
    id: 19,
    name: "Season City - Private Room",
    type: "Interior",
    image_url: [
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOWOb.jpg",
      "https://iili.io/hhOXbj.jpg",
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOwWQ.jpg",
      "https://iili.io/hhONsV.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOvg1.jpg",
    ],
    collab_detail: "ERBE Studio",
    type_detail: "Office Interior",
    location_detail: "Season City, Jakarta",
    status_detail: "Desain - Design ",
    IMAGES: [],
  },
  {
    id: 20,
    name: "FA Bedroom",
    type: "Interior",
    image_url: [
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOWOb.jpg",
      "https://iili.io/hhOXbj.jpg",
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOwWQ.jpg",
      "https://iili.io/hhONsV.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOvg1.jpg",
    ],
    collab_detail: "",
    type_detail: "",
    location_detail: "",
    status_detail: "",
    IMAGES: [],
  },
];

export const LISTDATARESIDENTIAL = [
  [
    {
      id: 0,
      name: "JD House",
      type: "Residential",
      image_url: [
        "https://iili.io/XtIsnI.jpg",
        "https://iili.io/XtILGt.jpg",
        "https://iili.io/XtIQ6X.jpg",
        "https://iili.io/XtItFn.jpg",
        "https://iili.io/XtIPZN.jpg",
      ],
    },
    {
      id: 1,
      name: "BA House",
      type: "Residential",
      image_url: [
        "https://iili.io/XycTmB.jpg",
        "https://iili.io/Xyc2bS.jpg",
        "https://iili.io/XycC0b.jpg",
        "https://iili.io/Xycz5Q.jpg",
        "https://iili.io/XycIeV.jpg",
        "https://iili.io/XycTmB.jpg",
        "https://iili.io/Xyc5LF.jpg",
        "https://iili.io/XycYqg.jpg",
        "https://iili.io/XycEep.jpg",
        "https://iili.io/XycGmN.jpg",
        "https://iili.io/XycWXt.jpg",
        "https://iili.io/XycXLX.jpg",
        "https://iili.io/Xyce2f.jpg",
        "https://iili.io/Xyc8p2.jpg",
        "https://iili.io/Xyc6Be.jpg",
        "https://iili.io/XycQYx.jpg",
        "https://iili.io/XyctpV.jpg",
        "https://iili.io/Xyl9CF.jpg",
        "https://iili.io/Xyl3Yv.jpg",
        "https://iili.io/XylFvR.jpg",
        "https://iili.io/XylBjI.jpg",
        "https://iili.io/XylT3G.jpg",
        "https://iili.io/XylRyl.jpg",
        "https://iili.io/XylYjS.jpg",
        "https://iili.io/XylG3b.jpg",
      ],
    },
    {
      id: 2,
      name: "PY House",
      type: "Residential",
      image_url: [
        "https://iili.io/hhVC3G.jpg",
        "https://iili.io/hhMp3J.jpg",
        "https://iili.io/hhMyYv.jpg",
        "https://iili.io/hhV9vR.jpg",
        "https://iili.io/hhVdTN.jpg",
        "https://iili.io/hhVKCX.jpg",
        "https://iili.io/hhVfGn.jpg",
        "https://iili.io/hhVq4s.jpg",
        "https://iili.io/hhVnaf.jpg",
        "https://iili.io/hhVov4.jpg",
        "https://iili.io/hhVxyl.jpg",
        "https://iili.io/hhVIu2.jpg",
        "https://iili.io/hhVTjS.jpg",
        "https://iili.io/hhVuZ7.jpg",
        "https://iili.io/hhVRn9.jpg",
        "https://iili.io/hhV5Ge.jpg",
        "https://iili.io/hhV76u.jpg",
        "https://iili.io/hhVa3b.jpg",
        "https://iili.io/hhVcaj.jpg",
        "https://iili.io/hhVl8x.jpg",
        "https://iili.io/hhV0yQ.jpg",
        "https://iili.io/hhVGwB.jpg",
        "https://iili.io/hhVMZP.jpg",
        "https://iili.io/hhVWn1.jpg",
        "https://iili.io/hhVXMF.jpg",
        "https://iili.io/hhVh6g.jpg",
        "https://iili.io/hhVwFa.jpg",
        "https://iili.io/hhVNcJ.jpg",
      ],
    },
    {
      id: 3,
      name: "AN House",
      type: "Residential",
      image_url: [
        "https://iili.io/hhVrMX.jpg",
        "https://iili.io/hhV8wN.jpg",
        "https://iili.io/hhVStI.jpg",
        "https://iili.io/hhVgnt.jpg",
        "https://iili.io/hhVrMX.jpg",
        "https://iili.io/hhV4Pn.jpg",
        "https://iili.io/hhVPFs.jpg",
        "https://iili.io/hhVicG.jpg",
        "https://iili.io/hhVsSf.jpg",
        "https://iili.io/hhVQ94.jpg",
        "https://iili.io/hhVZAl.jpg",
        "https://iili.io/hhVtN2.jpg",
        "https://iili.io/hhVDtS.jpg",
        "https://iili.io/hhVmo7.jpg",
        "https://iili.io/hhVpV9.jpg",
        "https://iili.io/hhVyPe.jpg",
        "https://iili.io/hhWHKu.jpg",
        "https://iili.io/hhWJcb.jpg",
        "https://iili.io/hhWdSj.jpg",
        "https://iili.io/hhW3Hx.jpg",
        "https://iili.io/hhWFAQ.jpg",
        "https://iili.io/hhWKNV.jpg",
        "https://iili.io/hhWfDB.jpg",
        "https://iili.io/hhWBoP.jpg",
        "https://iili.io/hhWCV1.jpg",
        "https://iili.io/hhWniF.jpg",
        "https://iili.io/hhWxKg.jpg",
        "https://iili.io/hhWzla.jpg",
        "https://iili.io/hhWIUJ.jpg",
        "https://iili.io/hhWuHv.jpg",
        "https://iili.io/hhWARR.jpg",
        "https://iili.io/hhWRNp.jpg",
        "https://iili.io/hhW5DN.jpg",
        "https://iili.io/hhWYxI.jpg",
        "https://iili.io/hhWciX.jpg",
        "https://iili.io/hhWEUG.jpg",
        "https://iili.io/hhWMJf.jpg",
        "https://iili.io/hhWVR4.jpg",
        "https://iili.io/hhWWOl.jpg",
      ],
    },
  ],
  [
    {
      id: 4,
      name: "NV House",
      type: "Residential",
      image_url: [
        "https://iili.io/hhW6zB.jpg",
        "https://iili.io/hhWk0u.jpg",
        "https://iili.io/hhWvUb.jpg",
        "https://iili.io/hhWSJj.jpg",
        "https://iili.io/hhWU5x.jpg",
        "https://iili.io/hhWgOQ.jpg",
        "https://iili.io/hhWrbV.jpg",
        "https://iili.io/hhWis1.jpg",
        "https://iili.io/hhWLqF.jpg",
        "https://iili.io/hhWQ0g.jpg",
        "https://iili.io/hhWZga.jpg",
        "https://iili.io/hhWDdJ.jpg",
        "https://iili.io/hhWb5v.jpg",
        "https://iili.io/hhWmeR.jpg",
        "https://iili.io/hhWpbp.jpg",
        "https://iili.io/hhX9zN.jpg",
        "https://iili.io/hhXHXI.jpg",
        "https://iili.io/hhXJst.jpg",
        "https://iili.io/hhX2qX.jpg",
        "https://iili.io/hhX31n.jpg",
        "https://iili.io/hhXFgs.jpg",
        "https://iili.io/hhXfdG.jpg",
        "https://iili.io/hhXq7f.jpg",
        "https://iili.io/hhXBe4.jpg",
        "https://iili.io/hhXCml.jpg",
      ],
    },
    {
      id: 5,
      name: "NL Villa",
      type: "Residential",
      image_url: [
        "https://iili.io/hhXjkv.jpg",
        "https://iili.io/hhXkQI.jpg",
        "https://iili.io/hhX8Bt.jpg",
      ],
    },
  ],
];

export const LISTDATACOMMERCIAL = [
  [
    {
      id: 6,
      name: "TD - Bakehouse",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhhfG1.jpg",
        "https://iili.io/hhXyYb.jpg",
        "https://iili.io/hhh9vj.jpg",
        "https://iili.io/hhhHyx.jpg",
        "https://iili.io/hhhdTQ.jpg",
        "https://iili.io/hhhdTQ.jpg",
        "https://iili.io/hhh3ZB.jpg",
        "https://iili.io/hhhKCP.jpg",
        "https://iili.io/hhhq6F.jpg",
        "https://iili.io/hhhC3g.jpg",
        "https://iili.io/hhhnaa.jpg",
        "https://iili.io/hhho8J.jpg",
      ],
    },
    {
      id: 7,
      name: "CD - SoHo",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhhRnI.jpg",
        "https://iili.io/hhhTjp.jpg",
        "https://iili.io/hhhuZN.jpg",
        "https://iili.io/hhh5Gt.jpg",
        "https://iili.io/hhh76X.jpg",
        "https://iili.io/hhhaFn.jpg",
      ],
    },
    {
      id: 8,
      name: "JXB - Bikehub",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhhNcu.jpg",
        "https://iili.io/hhh19f.jpg",
        "https://iili.io/hhhEu4.jpg",
        "https://iili.io/hhhGwl.jpg",
        "https://iili.io/hhhMt2.jpg",
        "https://iili.io/hhhWnS.jpg",
        "https://iili.io/hhhhP9.jpg",
        "https://iili.io/hhhwFe.jpg",
        "https://iili.io/hhhO8b.jpg",
        "https://iili.io/hhhk9j.jpg",
        "https://iili.io/hhhvAx.jpg",
        "https://iili.io/hhh8wQ.jpg",
        "https://iili.io/hhhStV.jpg",
        "https://iili.io/hhhgoB.jpg",
        "https://iili.io/hhhrMP.jpg",
      ],
    },
    {
      id: 9,
      name: "Sudirman - Shopping Ground",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhhZAv.jpg",
        "https://iili.io/hhhPKF.jpg",
        "https://iili.io/hhhicg.jpg",
        "https://iili.io/hhhsSa.jpg",
        "https://iili.io/hhhQHJ.jpg",
        "https://iili.io/hhhtNR.jpg",
        "https://iili.io/hhhDtp.jpg",
        "https://iili.io/hhhmoN.jpg",
        "https://iili.io/hhhpVI.jpg",
        "https://iili.io/hhhyPt.jpg",
      ],
    },
  ],
  [
    {
      id: 10,
      name: "Braga - Office",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhjJln.jpg",
        "https://iili.io/hhjHKX.jpg",
        "https://iili.io/hhjdSs.jpg",
        "https://iili.io/hhj3HG.jpg",
        "https://iili.io/hhjFRf.jpg",
        "https://iili.io/hhjKN4.jpg",
        "https://iili.io/hhjfDl.jpg",
        "https://iili.io/hhjBx2.jpg",
        "https://iili.io/hhjCVS.jpg",
        "https://iili.io/hhjni7.jpg",
      ],
    },
    {
      id: 11,
      name: "Muaro Jambi - Rest Area",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhjXbR.jpg",
        "https://iili.io/hhjuHb.jpg",
        "https://iili.io/hhjARj.jpg",
        "https://iili.io/hhjROx.jpg",
        "https://iili.io/hhj5DQ.jpg",
        "https://iili.io/hhjYxV.jpg",
        "https://iili.io/hhjaWB.jpg",
        "https://iili.io/hhjciP.jpg",
        "https://iili.io/hhj0f1.jpg",
        "https://iili.io/hhj10F.jpg",
        "https://iili.io/hhjEUg.jpg",
        "https://iili.io/hhjMJa.jpg",
        "https://iili.io/hhjV5J.jpg",
        "https://iili.io/hhjWOv.jpg",
        "https://iili.io/hhjjxp.jpg",
        "https://iili.io/hhjwWN.jpg",
        "https://iili.io/hhjNsI.jpg",
        "https://iili.io/hhjeft.jpg",
        "https://iili.io/hhjk0X.jpg",
      ],
    },
    {
      id: 12,
      name: "Rekathirta - Office",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhjSJs.jpg",
        "https://iili.io/hhjvgn.jpg",
        "https://iili.io/hhjU5G.jpg",
        "https://iili.io/hhjgef.jpg",
        "https://iili.io/hhjrb4.jpg",
        "https://iili.io/hhj6zl.jpg",
      ],
    },
    {
      id: 13,
      name: "Agro Jabar - Warehouse",
      type: "Commercial",
      image_url: [
        "https://iili.io/hhjpmx.jpg",
        "https://iili.io/hhjDdu.jpg",
        "https://iili.io/hhjb5b.jpg",
        "https://iili.io/hhjmej.jpg",
        "https://iili.io/hhjpmx.jpg",
        "https://iili.io/hhw9zQ.jpg",
        "https://iili.io/hhwHXV.jpg",
        "https://iili.io/hhwJLB.jpg",
        "https://iili.io/hhw2qP.jpg",
        "https://iili.io/hhw311.jpg",
        "https://iili.io/hhwFrF.jpg",
      ],
    },
  ],
];

export const LISTDATAHEALTH = [
  [
    {
      id: 14,
      name: "Dustira HD - Interior",
      type: "Healthcare",
      image_url: [
        "https://iili.io/hhwBkJ.jpg",
        "https://iili.io/hhwq7a.jpg",
        "https://iili.io/hhwCmv.jpg",
        "https://iili.io/hhwoIR.jpg",
        "https://iili.io/hhwxXp.jpg",
      ],
      collab_detail: "-",
      type_detail: "Lobby Interior",
      location_detail: "Cimahi, Indonesia",
      status_detail: "Selesai - Completed",
      area_detail: "100",
      IMAGES: [],
    },
    {
      id: 15,
      name: "Widaningshi - RSIA",
      type: "Healthcare",
      image_url: [
        "https://iili.io/hhw52n.jpg",
        "https://iili.io/hhwTBI.jpg",
        "https://iili.io/hhwu1t.jpg",
        "https://iili.io/hhwArX.jpg",
        "https://iili.io/hhw52n.jpg",
        "https://iili.io/hhw77s.jpg",
        "https://iili.io/hhwapf.jpg",
        "https://iili.io/hhw0hl.jpg",
        "https://iili.io/hhw1Q2.jpg",
        "https://iili.io/hhwGBS.jpg",
        "https://iili.io/hhwME7.jpg",
        "https://iili.io/hhwV49.jpg",
        "https://iili.io/hhwX2e.jpg",
        "https://iili.io/hhwhYu.jpg",
        "https://iili.io/hhwwpj.jpg",
        "https://iili.io/hhwr3F.jpg",
        "https://iili.io/hhwsTv.jpg",
        "https://iili.io/hhwLjR.jpg",
        "https://iili.io/hhwtCN.jpg",
        "https://iili.io/hhwDGI.jpg",
        "https://iili.io/hhwb4t.jpg",
        "https://iili.io/hhwp3X.jpg",
      ],
      collab_detail: "Nickola Fauzan",
      type_detail: "Interior",
      location_detail: "Garut, Indonesia",
      status_detail: "Desain - Design",
      area_detail: "400",
      IMAGES: [],
    },
    {
      id: 16,
      name: "KJ - Clinic",
      type: "Healthcare",
      image_url: [
        "https://iili.io/hhNfGS.jpg",
        "https://iili.io/hhwyan.jpg",
        "https://iili.io/hhN9vs.jpg",
        "https://iili.io/hhNHyG.jpg",
        "https://iili.io/hhNduf.jpg",
        "https://iili.io/hhN2j4.jpg",
        "https://iili.io/hhN3Zl.jpg",
        "https://iili.io/hhNKn2.jpg",
        "https://iili.io/hhNq67.jpg",
        "https://iili.io/hhNCF9.jpg",
        "https://iili.io/hhNnae.jpg",
        "https://iili.io/hhNo8u.jpg",
        "https://iili.io/hhNxyb.jpg",
      ],
      collab_detail: "-",
      type_detail: "Interior",
      location_detail: "Jamika, Bandung",
      status_detail: "Desain - Design (Under Construction)",
      area_detail: "100",
      IMAGES: [],
    },
  ],
];

export const LISTDATAINTERIOR = [
  [
    {
      id: 17,
      name: "NV - Kitchen",
      type: "Interior",
      image_url: [
        "https://iili.io/hhNDDx.jpg",
        "https://iili.io/hhNsSe.jpg",
        "https://iili.io/hhNZAb.jpg",
        "https://iili.io/hhNZAb.jpg",
        "https://iili.io/hhNZAb.jpg",
        "https://iili.io/hhNZAb.jpg",
        "https://iili.io/hhOJl1.jpg",
        "https://iili.io/hhOdUF.jpg",
        "https://iili.io/hhO3Hg.jpg",
        "https://iili.io/hhOFRa.jpg",
        "https://iili.io/hhOKOJ.jpg",
      ],
      collab_detail: "-",
      type_detail: "Kitchen Interior",
      location_detail: "Bintaro, Tangerang",
      status_detail: "Selesai - Completed",
      area_detail: "40",
      IMAGES: [],
    },
    {
      id: 18,
      name: "Petojo - Office",
      type: "Interior",
      image_url: [
        "https://iili.io/hhOARs.jpg",
        "https://iili.io/hhOCVp.jpg",
        "https://iili.io/hhOniN.jpg",
        "https://iili.io/hhOxfI.jpg",
        "https://iili.io/hhOzlt.jpg",
        "https://iili.io/hhOuJn.jpg",
        "https://iili.io/hhOROG.jpg",
        "https://iili.io/hhO5bf.jpg",
        "https://iili.io/hhOYx4.jpg",
        "https://iili.io/hhOaWl.jpg",
        "https://iili.io/hhOcs2.jpg",
        "https://iili.io/hhO0fS.jpg",
        "https://iili.io/hhO107.jpg",
      ],
      collab_detail: "-",
      type_detail: "Office Interior",
      location_detail: "Petojo, Jakarta",
      status_detail: "Desain - Design ",
      area_detail: "120",
      IMAGES: [],
    },
    {
      id: 19,
      name: "Season City - Private Room",
      type: "Interior",
      image_url: [
        "https://iili.io/hhOjzx.jpg",
        "https://iili.io/hhOWOb.jpg",
        "https://iili.io/hhOXbj.jpg",
        "https://iili.io/hhOjzx.jpg",
        "https://iili.io/hhOwWQ.jpg",
        "https://iili.io/hhONsV.jpg",
        "https://iili.io/hhOeqB.jpg",
        "https://iili.io/hhOeqB.jpg",
        "https://iili.io/hhOvg1.jpg",
      ],
      collab_detail: "ERBE Studio",
      type_detail: "Office Interior",
      location_detail: "Season City, Jakarta",
      status_detail: "Desain - Design ",
      IMAGES: [],
    },
    {
      id: 20,
      name: "FA Bedroom",
      type: "Interior",
      image_url: [
        "https://iili.io/hhOjzx.jpg",
        "https://iili.io/hhOWOb.jpg",
        "https://iili.io/hhOXbj.jpg",
        "https://iili.io/hhOjzx.jpg",
        "https://iili.io/hhOwWQ.jpg",
        "https://iili.io/hhONsV.jpg",
        "https://iili.io/hhOeqB.jpg",
        "https://iili.io/hhOeqB.jpg",
        "https://iili.io/hhOvg1.jpg",
      ],
      collab_detail: "",
      type_detail: "",
      location_detail: "",
      status_detail: "",
      IMAGES: [],
    },
  ],
];

export const SIDEDATARESIDENTIAL = [
  {
    id: 0,
    name: "JD House",
    type: "Residential",
    image_url: "https://iili.io/XtILGt.jpg",
  },
  {
    id: 1,
    name: "BA House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 2,
    name: "PY House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 3,
    name: "AN House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 4,
    name: "NV House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 5,
    name: "NL Villa",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
];

export const SIDEDATACOMMERCIAL = [
  {
    id: 6,
    name: "TD - Bakehouse",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhfG1.jpg",
      "https://iili.io/hhXyYb.jpg",
      "https://iili.io/hhh9vj.jpg",
      "https://iili.io/hhhHyx.jpg",
      "https://iili.io/hhhdTQ.jpg",
      "https://iili.io/hhhdTQ.jpg",
      "https://iili.io/hhh3ZB.jpg",
      "https://iili.io/hhhKCP.jpg",
      "https://iili.io/hhhq6F.jpg",
      "https://iili.io/hhhC3g.jpg",
      "https://iili.io/hhhnaa.jpg",
      "https://iili.io/hhho8J.jpg",
    ],
  },
  {
    id: 7,
    name: "CD - SoHo",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhRnI.jpg",
      "https://iili.io/hhhTjp.jpg",
      "https://iili.io/hhhuZN.jpg",
      "https://iili.io/hhh5Gt.jpg",
      "https://iili.io/hhh76X.jpg",
      "https://iili.io/hhhaFn.jpg",
    ],
  },
  {
    id: 8,
    name: "JXB - Bikehub",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhNcu.jpg",
      "https://iili.io/hhh19f.jpg",
      "https://iili.io/hhhEu4.jpg",
      "https://iili.io/hhhGwl.jpg",
      "https://iili.io/hhhMt2.jpg",
      "https://iili.io/hhhWnS.jpg",
      "https://iili.io/hhhhP9.jpg",
      "https://iili.io/hhhwFe.jpg",
      "https://iili.io/hhhO8b.jpg",
      "https://iili.io/hhhk9j.jpg",
      "https://iili.io/hhhvAx.jpg",
      "https://iili.io/hhh8wQ.jpg",
      "https://iili.io/hhhStV.jpg",
      "https://iili.io/hhhgoB.jpg",
      "https://iili.io/hhhrMP.jpg",
    ],
  },
  {
    id: 9,
    name: "Sudirman - Shopping Ground",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhhZAv.jpg",
      "https://iili.io/hhhPKF.jpg",
      "https://iili.io/hhhicg.jpg",
      "https://iili.io/hhhsSa.jpg",
      "https://iili.io/hhhQHJ.jpg",
      "https://iili.io/hhhtNR.jpg",
      "https://iili.io/hhhDtp.jpg",
      "https://iili.io/hhhmoN.jpg",
      "https://iili.io/hhhpVI.jpg",
      "https://iili.io/hhhyPt.jpg",
    ],
  },
  {
    id: 10,
    name: "Braga - Office",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjJln.jpg",
      "https://iili.io/hhjHKX.jpg",
      "https://iili.io/hhjdSs.jpg",
      "https://iili.io/hhj3HG.jpg",
      "https://iili.io/hhjFRf.jpg",
      "https://iili.io/hhjKN4.jpg",
      "https://iili.io/hhjfDl.jpg",
      "https://iili.io/hhjBx2.jpg",
      "https://iili.io/hhjCVS.jpg",
      "https://iili.io/hhjni7.jpg",
    ],
  },
  {
    id: 11,
    name: "Muaro Jambi - Rest Area",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjXbR.jpg",
      "https://iili.io/hhjuHb.jpg",
      "https://iili.io/hhjARj.jpg",
      "https://iili.io/hhjROx.jpg",
      "https://iili.io/hhj5DQ.jpg",
      "https://iili.io/hhjYxV.jpg",
      "https://iili.io/hhjaWB.jpg",
      "https://iili.io/hhjciP.jpg",
      "https://iili.io/hhj0f1.jpg",
      "https://iili.io/hhj10F.jpg",
      "https://iili.io/hhjEUg.jpg",
      "https://iili.io/hhjMJa.jpg",
      "https://iili.io/hhjV5J.jpg",
      "https://iili.io/hhjWOv.jpg",
      "https://iili.io/hhjjxp.jpg",
      "https://iili.io/hhjwWN.jpg",
      "https://iili.io/hhjNsI.jpg",
      "https://iili.io/hhjeft.jpg",
      "https://iili.io/hhjk0X.jpg",
    ],
  },
  {
    id: 12,
    name: "Rekathirta - Office",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjSJs.jpg",
      "https://iili.io/hhjvgn.jpg",
      "https://iili.io/hhjU5G.jpg",
      "https://iili.io/hhjgef.jpg",
      "https://iili.io/hhjrb4.jpg",
      "https://iili.io/hhj6zl.jpg",
    ],
  },
  {
    id: 13,
    name: "Agro Jabar - Warehouse",
    type: "Commercial",
    image_url: [
      "https://iili.io/hhjpmx.jpg",
      "https://iili.io/hhjDdu.jpg",
      "https://iili.io/hhjb5b.jpg",
      "https://iili.io/hhjmej.jpg",
      "https://iili.io/hhjpmx.jpg",
      "https://iili.io/hhw9zQ.jpg",
      "https://iili.io/hhwHXV.jpg",
      "https://iili.io/hhwJLB.jpg",
      "https://iili.io/hhw2qP.jpg",
      "https://iili.io/hhw311.jpg",
      "https://iili.io/hhwFrF.jpg",
    ],
  },
];

export const SIDEDATAHEALTH = [
  {
    id: 14,
    name: "Dustira HD - Interior",
    type: "Healthcare",
    image_url: [
      "https://iili.io/hhwBkJ.jpg",
      "https://iili.io/hhwq7a.jpg",
      "https://iili.io/hhwCmv.jpg",
      "https://iili.io/hhwoIR.jpg",
      "https://iili.io/hhwxXp.jpg",
    ],
  },
  {
    id: 15,
    name: "Widaningshi - RSIA",
    type: "Healthcare",
    image_url: [
      "https://iili.io/hhw52n.jpg",
      "https://iili.io/hhwTBI.jpg",
      "https://iili.io/hhwu1t.jpg",
      "https://iili.io/hhwArX.jpg",
      "https://iili.io/hhw52n.jpg",
      "https://iili.io/hhw77s.jpg",
      "https://iili.io/hhwapf.jpg",
      "https://iili.io/hhw0hl.jpg",
      "https://iili.io/hhw1Q2.jpg",
      "https://iili.io/hhwGBS.jpg",
      "https://iili.io/hhwME7.jpg",
      "https://iili.io/hhwV49.jpg",
      "https://iili.io/hhwX2e.jpg",
      "https://iili.io/hhwhYu.jpg",
      "https://iili.io/hhwwpj.jpg",
      "https://iili.io/hhwr3F.jpg",
      "https://iili.io/hhwsTv.jpg",
      "https://iili.io/hhwLjR.jpg",
      "https://iili.io/hhwtCN.jpg",
      "https://iili.io/hhwDGI.jpg",
      "https://iili.io/hhwb4t.jpg",
      "https://iili.io/hhwp3X.jpg",
    ],
  },
  {
    id: 16,
    name: "KJ - Clinic",
    type: "Healthcare",
    image_url: [
      "https://iili.io/hhNfGS.jpg",
      "https://iili.io/hhwyan.jpg",
      "https://iili.io/hhN9vs.jpg",
      "https://iili.io/hhNHyG.jpg",
      "https://iili.io/hhNduf.jpg",
      "https://iili.io/hhN2j4.jpg",
      "https://iili.io/hhN3Zl.jpg",
      "https://iili.io/hhNKn2.jpg",
      "https://iili.io/hhNq67.jpg",
      "https://iili.io/hhNCF9.jpg",
      "https://iili.io/hhNnae.jpg",
      "https://iili.io/hhNo8u.jpg",
      "https://iili.io/hhNxyb.jpg",
    ],
  },
];

export const SIDEDATAINTERIOR = [
  {
    id: 17,
    name: "NV - Kitchen",
    type: "Interior",
    image_url: [
      "https://iili.io/hhNDDx.jpg",
      "https://iili.io/hhNsSe.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhNZAb.jpg",
      "https://iili.io/hhOJl1.jpg",
      "https://iili.io/hhOdUF.jpg",
      "https://iili.io/hhO3Hg.jpg",
      "https://iili.io/hhOFRa.jpg",
      "https://iili.io/hhOKOJ.jpg",
    ],
  },
  {
    id: 18,
    name: "Petojo - Office",
    type: "Interior",
    image_url: [
      "https://iili.io/hhOARs.jpg",
      "https://iili.io/hhOCVp.jpg",
      "https://iili.io/hhOniN.jpg",
      "https://iili.io/hhOxfI.jpg",
      "https://iili.io/hhOzlt.jpg",
      "https://iili.io/hhOuJn.jpg",
      "https://iili.io/hhOROG.jpg",
      "https://iili.io/hhO5bf.jpg",
      "https://iili.io/hhOYx4.jpg",
      "https://iili.io/hhOaWl.jpg",
      "https://iili.io/hhOcs2.jpg",
      "https://iili.io/hhO0fS.jpg",
      "https://iili.io/hhO107.jpg",
    ],
  },
  {
    id: 19,
    name: "Season City - Private Room",
    type: "Interior",
    image_url: [
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOWOb.jpg",
      "https://iili.io/hhOXbj.jpg",
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOwWQ.jpg",
      "https://iili.io/hhONsV.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOvg1.jpg",
    ],
  },
  {
    id: 20,
    name: "FA Bedroom",
    type: "Interior",
    image_url: [
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOWOb.jpg",
      "https://iili.io/hhOXbj.jpg",
      "https://iili.io/hhOjzx.jpg",
      "https://iili.io/hhOwWQ.jpg",
      "https://iili.io/hhONsV.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOeqB.jpg",
      "https://iili.io/hhOvg1.jpg",
    ],
  },
];

export const LISTIMGTEAMIZA = [
  "https://iili.io/waKKrX.jpg",
  "https://iili.io/waKJXp.jpg",
  "https://iili.io/waKzhl.jpg",
];

export const LISTIMGTEAMLUDO = [
  "https://iili.io/waKF1t.jpg",
  "https://iili.io/waFrej.jpg",
  "https://iili.io/waF4mx.jpg",
  "https://iili.io/waFiXV.jpg",
  "https://iili.io/waFsLB.jpg",
  "https://iili.io/waFQqP.jpg",
  "https://iili.io/waFZ11.jpg",
  "https://iili.io/waK72e.jpg",
  "https://iili.io/waKYYu.jpg",
];

export const LISTIMGTEAMISAN = [
  "https://iili.io/waKIQ2.jpg",
  "https://iili.io/waFPzQ.jpg",
  "https://iili.io/waFtrF.jpg",
  "https://iili.io/waFbdg.jpg",
  "https://iili.io/waFm7a.jpg",
  "https://iili.io/waKHIR.jpg",
  "https://iili.io/waFymv.jpg",
  "https://iili.io/waKq2n.jpg",
  "https://iili.io/waKB7s.jpg",
  "https://iili.io/waKCkG.jpg",
  "https://iili.io/waKuBS.jpg",
  "https://iili.io/waKAE7.jpg",
  "https://iili.io/waKR49.jpg",
];

export const LISTTYPEWORK = [
  {
    name: "Architecture",
    img: "https://iili.io/waIvZg.jpg",
    data: ["Design", "Build", "Design and Build"],
  },
  {
    name: "Interior",
    img: "https://iili.io/waI6ap.jpg",
    data: ["Design", "Design and Build"],
  },
  {
    name: "3D Rendering (by RENDER HELP)",
    img: "https://iili.io/waISna.jpg",
    data: ["Interior", "Exterior"],
  },
];

export const LISTWORKFLOW = [
  {
    name: "Design Prelim",
    img: "https://iili.io/waI4FR.jpg",
    data: [
      "Early Brief",
      "Moodboard Proposal & Surat Penawaran",
      "Project Agreement",
      "Design Concept (3 Revisions Max",
    ],
  },
  {
    name: "Technical Design",
    img: "https://iili.io/waIg6v.jpg",
    data: ["Design Development", "BED", "BoQ / RAB"],
  },
  {
    name: "Construction",
    img: "https://iili.io/waIs9I.jpg",
    data: ["Tender", "Groundbreaking", "Supervisi"],
  },
];
