export const MENUITEMS = [
  {
    title: "Projects",
    submenu: ["Residential", "Commercial", "Healthcare", "Interior"],
  },
  {
    title: "About",
  },
  {
    title: "Contact",
  },
  {
    title: "Scope of Work",
  },
];

export const BUILDINGDATAHOMEPAGE = [
  {
    id: 3,
    name: "AN House",
    type: "Residential",
    image_url: [
      "https://iili.io/hhVrMX.jpg",
      "https://iili.io/hhV8wN.jpg",
      "https://iili.io/hhVStI.jpg",
      "https://iili.io/hhVgnt.jpg",
      "https://iili.io/hhVrMX.jpg",
      "https://iili.io/hhV4Pn.jpg",
      "https://iili.io/hhVPFs.jpg",
      "https://iili.io/hhVicG.jpg",
      "https://iili.io/hhVsSf.jpg",
      "https://iili.io/hhVQ94.jpg",
      "https://iili.io/hhVZAl.jpg",
      "https://iili.io/hhVtN2.jpg",
      "https://iili.io/hhVDtS.jpg",
      "https://iili.io/hhVmo7.jpg",
      "https://iili.io/hhVpV9.jpg",
      "https://iili.io/hhVyPe.jpg",
      "https://iili.io/hhWHKu.jpg",
      "https://iili.io/hhWJcb.jpg",
      "https://iili.io/hhWdSj.jpg",
      "https://iili.io/hhW3Hx.jpg",
      "https://iili.io/hhWFAQ.jpg",
      "https://iili.io/hhWKNV.jpg",
      "https://iili.io/hhWfDB.jpg",
      "https://iili.io/hhWBoP.jpg",
      "https://iili.io/hhWCV1.jpg",
      "https://iili.io/hhWniF.jpg",
      "https://iili.io/hhWxKg.jpg",
      "https://iili.io/hhWzla.jpg",
      "https://iili.io/hhWIUJ.jpg",
      "https://iili.io/hhWuHv.jpg",
      "https://iili.io/hhWARR.jpg",
      "https://iili.io/hhWRNp.jpg",
      "https://iili.io/hhW5DN.jpg",
      "https://iili.io/hhWYxI.jpg",
      "https://iili.io/hhWciX.jpg",
      "https://iili.io/hhWEUG.jpg",
      "https://iili.io/hhWMJf.jpg",
      "https://iili.io/hhWVR4.jpg",
      "https://iili.io/hhWWOl.jpg",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
    ],
  },
  {
    id: 1,
    name: "BA House",
    type: "Residential",
    image_url: [
      "https://iili.io/XycIeV.jpg",
      "https://iili.io/Xyc2bS.jpg",
      "https://iili.io/XycC0b.jpg",
      "https://iili.io/Xycz5Q.jpg",
      "https://iili.io/XycIeV.jpg",
      "https://iili.io/XycTmB.jpg",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
      // "",
    ],
  },
  {
    id: 1, //ganti FA bedroom
    name: "BA House",
    type: "Residential",
    image_url: "https://iili.io/hhVrMX.jpg",
  },
  {
    id: 6,
    name: "TD - Bakehouse",
    type: "Commercial",
    image_url: "https://iili.io/hhhq6F.jpg",
  },
  {
    id: 16,
    name: "KJ - Clinic",
    type: "Healthcare",
    image_url: "https://iili.io/hhwyan.jpg",
  },
];

export const BUILDINGDATA = [
  {
    id: 0,
    name: "JD House",
    type: "Residential",
    image_url: "https://iili.io/XtILGt.jpg",
  },
  {
    id: 1,
    name: "BA House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 2,
    name: "PY House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 3,
    name: "AN House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 4,
    name: "NV House",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 5,
    name: "NL Villa",
    type: "Residential",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 6,
    name: "TD - Bakehouse",
    type: "Commercial",
    image_url: "https://iili.io/XtILGt.jpg",
  },
  {
    id: 7,
    name: "CD - SoHo",
    type: "Commercial",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 8,
    name: "JXB - Bikehub",
    type: "Commercial",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 9,
    name: "Sudirman - Shopping Ground",
    type: "Commercial",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 10,
    name: "Braga - Office",
    type: "Commercial",
    image_url: "https://iili.io/XycTmB.jpg",
  },
  {
    id: 11,
    name: "Muaro Jambi - Rest Area",
    type: "Commercial",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 12,
    name: "Rekathirta - Office",
    type: "Commercial",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 13,
    name: "Agro Jabar - Warehouse",
    type: "Commercial",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 14,
    name: "Dustira HD - Interior",
    type: "Healthcare",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 15,
    name: "Widaningshi - RSIA",
    type: "Healthcare",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 16,
    name: "KJ - Clinic",
    type: "Healthcare",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 17,
    name: "NV - Kitchen",
    type: "Interior",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 18,
    name: "Petojo - Office",
    type: "Interior",
    image_url: "https://iili.io/XycTmCommercial",
  },
  {
    id: 19,
    name: "Season City - Private Room",
    type: "Interior",
    image_url: "https://iili.io/XycTmCommercial",
  },
];
